### ISSUE TITLE
Variant_search multi language

### ISSUE THREAD

**Issue by CasVissers-360ERP** [luca-vercelli/odoo-modules#4]
Hi,

In a multi language Odoo set-up we generate the var_desc in English. But if a user works in ie. Dutch the user want's to search on the Dutch name of the description/variant not the English one.

Would it be possible to fix this?

With kind regards,
Cas

**Comment by luca-vercelli** [comment]
Hi,
I think this is not fast to achieve. You should have another table product_var_desc, that gives one different var_desc for every language.

**Comment by CasVissers-360ERP** [comment]
@luca-vercelli 
Thank you for your answer. Seems logical.

**Comment by luca-vercelli** [comment]
Anyway, thank you for your suggestion. I will leave this issue open, maybe in the future I (or somebody else) could work on it.

**Comment by CasVissers-360ERP** [comment]
Maybe it's an idea to let the user decide in what language the description should be generated? Most of the time there is 1 main language in a system with supporting languages for reports.
