### ISSUE TITLE
Variant_search onchange name / attribute

### ISSUE THREAD

**Issue by CasVissers-360ERP** [luca-vercelli/odoo-modules#5]
Hi,

Shouldn't the var_desc be recomputed onchange of the product name or attributes?

Cas

**Comment by luca-vercelli** [comment]
Yes it should

**Comment by luca-vercelli** [comment]
Just checked, there is really a bug here. Weird I had never noticed.

**Comment by luca-vercelli** [comment]
Just fixed on 11.0

**Comment by CasVissers-360ERP** [comment]
Thnx!
