### ISSUE TITLE
Migration to Odoo v12

### ISSUE THREAD

**Issue by FelipeEnriqueGG** [luca-vercelli/odoo-modules#6]
Are you going to migrate the module "Variant_search" to v12?

**Comment by luca-vercelli** [comment]
Not yet, sorry

Il lun 27 mag 2019, 18:44 Felipe Enrique Garcia Guitron <
notifications@github.com> ha scritto:

**Comment by FelipeEnriqueGG** [comment]
i already tried it in the v12 and it worked just fine. So can you create the branch  for v12, and tell me the version for the Manifest.py?

**Comment by luca-vercelli** [comment]
Done.

https://apps.odoo.com/apps/modules/12.0/variant_search/
version 1.2

regards
